# Generated by Django 4.1.3 on 2023-01-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='min_group',
            field=models.IntegerField(choices=[(10, 'mittelgroße Gruppe'), (2, 'sehr kleiner Gruppe'), (5, 'kleine Gruppe'), (20, 'sehr große Gruppe'), (0, 'ohne Limit')], default=1),
            preserve_default=False,
        ),
    ]
