# Generated by Django 4.1.3 on 2023-01-31 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_min_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 10, 11, 17, 290166, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
