# Generated by Django 4.1.3 on 2023-01-31 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorien'},
        ),
    ]
